# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Asncli < Formula
  desc "Asana CLI - human-readable output by default, JSON for automation"
  homepage "https://github.com/daikw/asncli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/daikw/asncli/releases/download/v0.1.0/asncli_Darwin_x86_64.tar.gz"
      sha256 "5ca45e21fa8a808342b9774203cb17c8f88f4b7837c911384b9a8d0c079925b2"

      define_method(:install) do
        bin.install "asn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/daikw/asncli/releases/download/v0.1.0/asncli_Darwin_arm64.tar.gz"
      sha256 "c7ff7babbe834c75cd7d5e2bef66f91b41918978bd0bfa917e87e2948461157a"

      define_method(:install) do
        bin.install "asn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/daikw/asncli/releases/download/v0.1.0/asncli_Linux_x86_64.tar.gz"
      sha256 "6c47526f0a58540eb09590cfc40d070c279ddb555832764f2fc93609f1e8ec2a"
      define_method(:install) do
        bin.install "asn"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/daikw/asncli/releases/download/v0.1.0/asncli_Linux_armv6.tar.gz"
      sha256 "d0f86124ba71f2981c9ce5a80ae69cddb6f046fd60c149eecbba3a103f260f6f"
      define_method(:install) do
        bin.install "asn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/daikw/asncli/releases/download/v0.1.0/asncli_Linux_arm64.tar.gz"
      sha256 "5bbf9e5b120424d456d1484f3891fa9d74645ca97a02ce0b0012356728c1a8aa"
      define_method(:install) do
        bin.install "asn"
      end
    end
  end

  test do
    system "#{bin}/asn", "--help"
  end
end
