# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Asncli < Formula
  desc "Asana CLI - human-readable output by default, JSON for automation"
  homepage "https://github.com/daikw/asncli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/daikw/asncli/releases/download/v0.2.0/asncli_Darwin_x86_64.tar.gz"
      sha256 "9fc73f49a6bd149802e08ac32de8ed1860fd43fae485e2e6d3157d5fa1c2ab9a"

      define_method(:install) do
        bin.install "asn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/daikw/asncli/releases/download/v0.2.0/asncli_Darwin_arm64.tar.gz"
      sha256 "26af81586ff0b668f0e6a30cb73ab73102bbb8d1dee1fe36b5fec11b4ad2c8de"

      define_method(:install) do
        bin.install "asn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/daikw/asncli/releases/download/v0.2.0/asncli_Linux_x86_64.tar.gz"
      sha256 "b5f8ac352c96a6f6e70f026bdd6e90015b0bb546015b7c5ab88be5683a322ce2"
      define_method(:install) do
        bin.install "asn"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/daikw/asncli/releases/download/v0.2.0/asncli_Linux_armv6.tar.gz"
      sha256 "66e7b9f4b8b327a242d5e36400c3f4501a9b04a494c10ad542ed82777fc88f6f"
      define_method(:install) do
        bin.install "asn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/daikw/asncli/releases/download/v0.2.0/asncli_Linux_arm64.tar.gz"
      sha256 "5a08b473081954c31d5fa6a6a01d39615ebc5e8dd2c786ec0611a8e133cb1601"
      define_method(:install) do
        bin.install "asn"
      end
    end
  end

  test do
    system "#{bin}/asn", "--help"
  end
end
