# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccpersona < Formula
  desc "Claude Code Persona System - Automatically apply different personas to Claude Code sessions"
  homepage "https://github.com/daikw/ccpersona"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/daikw/ccpersona/releases/download/v0.1.7/ccpersona_Darwin_x86_64.tar.gz"
      sha256 "c58ec48574052e1ef3e276d48c97208c336ff13e5bd0e25c2f2e4212bd573c2e"

      def install
        bin.install "ccpersona"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/daikw/ccpersona/releases/download/v0.1.7/ccpersona_Darwin_arm64.tar.gz"
      sha256 "a8b7bff5b01ba2838a7600448692528d355e9bba68d64f7f522db52cdc172eb7"

      def install
        bin.install "ccpersona"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/daikw/ccpersona/releases/download/v0.1.7/ccpersona_Linux_x86_64.tar.gz"
      sha256 "80557003663e860faa3deebf7a4e1c8ad1e3748badff6044473a4168f9a926af"
      def install
        bin.install "ccpersona"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/daikw/ccpersona/releases/download/v0.1.7/ccpersona_Linux_armv6.tar.gz"
      sha256 "69b3ca03dab97af0e844730071893f5f96a95fb0e6487a222b02dce0883baf64"
      def install
        bin.install "ccpersona"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/daikw/ccpersona/releases/download/v0.1.7/ccpersona_Linux_arm64.tar.gz"
      sha256 "8250abfdd8a89c45cca592115cd0eb6ce58915ecd8e2921d2ccb6fe0df4c3c84"
      def install
        bin.install "ccpersona"
      end
    end
  end

  test do
    system "#{bin}/ccpersona", "--version"
  end
end
