# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccpersona < Formula
  desc "Claude Code Persona System - Automatically apply different personas to Claude Code sessions"
  homepage "https://github.com/daikw/ccpersona"
  version "0.1.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/daikw/ccpersona/releases/download/v0.1.11/ccpersona_Darwin_x86_64.tar.gz"
      sha256 "e89387f68412709d1ade656fefb0340fad889461bd6ae1b93636a3dfd46b5e9c"

      def install
        bin.install "ccpersona"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/daikw/ccpersona/releases/download/v0.1.11/ccpersona_Darwin_arm64.tar.gz"
      sha256 "909f00724cc073ec22fc84e1e5faf5ee60172299fbf43e7174c88c851f9a2c7b"

      def install
        bin.install "ccpersona"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/daikw/ccpersona/releases/download/v0.1.11/ccpersona_Linux_x86_64.tar.gz"
      sha256 "f48872b2bf2e65ba497dcb2a0180c7194ecde15e3547246cc368e401a35d9376"
      def install
        bin.install "ccpersona"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/daikw/ccpersona/releases/download/v0.1.11/ccpersona_Linux_armv6.tar.gz"
      sha256 "5ad629ca4631b51ee17efe04a6d41d64f912b91f67fcdda5d7d61af2aa3dc980"
      def install
        bin.install "ccpersona"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/daikw/ccpersona/releases/download/v0.1.11/ccpersona_Linux_arm64.tar.gz"
      sha256 "cd15e23558d7501278abe2742d5dca9a41bff90293d861fe69a29df0582f677e"
      def install
        bin.install "ccpersona"
      end
    end
  end

  test do
    system "#{bin}/ccpersona", "--version"
  end
end
