# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdstrip < Formula
  desc "Strip Markdown formatting from text"
  homepage "https://github.com/daikw/mdstrip"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/daikw/mdstrip/releases/download/v0.2.1/mdstrip_Darwin_x86_64.tar.gz"
      sha256 "16bfad265e608a0927bd4cfa1f1832e2d33cd28afdaf5cd6ff300d4ab785f99c"

      def install
        bin.install "mdstrip"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/daikw/mdstrip/releases/download/v0.2.1/mdstrip_Darwin_arm64.tar.gz"
      sha256 "0b443fd464046cd90d4c0d5fcc7442baef247719fa957d679590417feb17b193"

      def install
        bin.install "mdstrip"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/daikw/mdstrip/releases/download/v0.2.1/mdstrip_Linux_x86_64.tar.gz"
      sha256 "1a82dc8e63407289b64b49df4478407003bc23c4bace96c774c0e20f73e1788b"
      def install
        bin.install "mdstrip"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/daikw/mdstrip/releases/download/v0.2.1/mdstrip_Linux_armv6.tar.gz"
      sha256 "d41e8d9c6da3564e55ef40cb9906aa9ae5741fefc20aeda950f6a5b3a4443727"
      def install
        bin.install "mdstrip"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/daikw/mdstrip/releases/download/v0.2.1/mdstrip_Linux_arm64.tar.gz"
      sha256 "67892261f2bf59ecaeca23885d10e1f9087bf692f8f1bdb8b28aa2945bf0de80"
      def install
        bin.install "mdstrip"
      end
    end
  end

  test do
    system "#{bin}/mdstrip", "--version"
  end
end
